// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgqnEcwRfo3egs7KTE99tI4yWSyqDV7Zw',
    appId: '1:622631828696:android:889fbed0792af9532d2bad',
    messagingSenderId: '622631828696',
    projectId: 'mydaet',
    storageBucket: 'mydaet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Wktoh6-7dYuBQRbJ7Ca3uM_X7_QA0qI',
    appId: '1:622631828696:ios:8d1d395df5d262a32d2bad',
    messagingSenderId: '622631828696',
    projectId: 'mydaet',
    storageBucket: 'mydaet.firebasestorage.app',
    iosBundleId: 'com.example.mydaet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9aPbAsceliukQQCfv3m_hvMsIbtMqHBI',
    appId: '1:622631828696:web:b45ec2ef1dd3297e2d2bad',
    messagingSenderId: '622631828696',
    projectId: 'mydaet',
    authDomain: 'mydaet.firebaseapp.com',
    storageBucket: 'mydaet.firebasestorage.app',
    measurementId: 'G-3B5ZQTKDQK',
  );

}